feet=int(input("enter the length of the feet :"))
print("click 1 to convert feet into inches")
print("click 2 to convert feet into yards")
print("click 3 to convert feet into miles")
print("click 4 to convert feet into millimeters")
print("click 5 to convert feet into centimeters")
print("click 6 to convert feet into meters")
print("click 7 to convert feet into kilometers")
ch=int(input("enter your choice :"))
match ch :
    case 1 :print(float(12*feet),"inches")
    case 2 :print(float(0.33*feet),"yards")
    case 3 :print(float(0.000189394*feet),"miles")
    case 4 :print(float(304.8*feet),"millimeters")
    case 5 :print(float(30.48*feet),"centimeters")
    case 6 :print(float(0.3048*feet),"meters")
    case 7 :print(float(0.0003048*feet),"kilometers")